import { StyleSheet } from "react-native";

const ShootingStyle = StyleSheet.create({
  container: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 30,
  },
  topinfo: {
    backgroundColor: "#48cff4",
    borderRadius: 30,
    width: 375,
    height: 441,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  mainphoto: {
    width: 300,
    height: 300,
  },
  content: {
    width: 300,
    height: 300,
  },
  elipse2: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    boxSizing: "border-box",
    display: "flex",
    width: 300,
    height: 300,
    borderRadius: 100,
    borderWidth: 3,
    borderColor: "rgba(255, 255, 255, 0.2)",

  },
  elipse: {
    flexDirection: "column",
    justifyContent: "center",
    display: "flex",
    alignItems: "center",
    width: 275,
    height: 275,
    borderRadius: 100,
    backgroundColor: "#FFFFFF",
  },
  camera: {
    width: 250,
    height: 250,
    borderRadius: 100,
    overflow: 'hidden',
  },
  selectedImage: {
    width: 250,
    height: 250,
    borderRadius: 100,
  },
  defaultImage: {
    width: 250,
    height: 250,
    borderRadius: 100,
  },
  bottominfo: {
    backgroundColor: "#FFFFFF",
    width: 375,
    height: 371,
    borderRadius: 30,
    justifyContent: "center",
    display: "flex",
    alignItems: "center",
  },
  buttonmenu: {
    width: 375,
    height: 371,
    borderRadius: 30,
    justifyContent: "center",
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
  },
  upload: {
    width: 375,
    height: 100,
    flexDirection: "row",
    justifyContent: "center",
    display: "flex",
    alignItems: "center",
    padding: 10,
    gap: 44,
  },
  rectangleB: {
    width: 100,
    height: 100,
    backgroundColor: "#71ddff",
    padding: 30,
    fontSize: 42,
    borderRadius: 100,
    cursor: "pointer",
    color: "rgba(255, 255, 255, 0.4)",
    alignItems: "center",
    justifyContent: "center",
  },
  test: {
    width: 375,
    height: 70,
    flexDirection: "row",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
    gap: 44,
  },
  rectangleC: {
    width: 150,
    height: 70,
    backgroundColor: "#71ddff",
    borderRadius: 20,
    cursor: "pointer",
    justifyContent: "center",
    alignItems: "center",
  }, 
  testText: {
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 17,
    lineHeight: 70,
    display: "flex",
    alignItems: "flex-end",
    color: "rgba(0, 0, 0, 0.4)",
    justifyContent: "center",
  },
});

export default ShootingStyle;
